apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "person-service.fullname" . }}
  labels:
    {{- include "person-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "person-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "person-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DATASOURCE_URL
            value: "jdbc:mysql://mysql:3306/peopledb"
          - name: DATASOURCE_USERNAME
            value: "root"
          - name: DATASOURCE_PASSWORD
            value: "P@ssw0rd"
          - name: LUCENE_INDEX_DIR
            value: "/lucene-data"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          volumeMounts:
          - mountPath: "/lucene-data"
            name: lucene-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: lucene-data
          persistentVolumeClaim:
            claimName: pvc-lucene-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
